import type { StudentEvent } from "./types";

export const studentEvents: StudentEvent[] = [
  {
    id: "1",
    title: "Sports Festival",
    emoji: "🏆",
    organization: "Supreme Student Council",
    posterName: "Sample Poster",
    posterCollege: "College of Computing Studies",
    date: "Mar 20",
    time: "7PM",
    venue: "Gymnasium",
    day: 20,
  },
  {
    id: "2",
    title: "Seminar",
    emoji: "📚",
    organization: "Organization A",
    posterName: "Sample Poster",
    posterCollege: "",
    date: "Mar 21",
    time: "6PM",
    venue: "AVR",
    day: 21,
  },
  {
    id: "3",
    title: "Concert",
    emoji: "🎸",
    organization: "Organization B",
    posterName: "Sample Poster",
    posterCollege: "",
    date: "Mar 25",
    time: "8PM",
    venue: "Field",
    day: 25,
  },
  {
    id: "4",
    title: "Workshop",
    emoji: "💻",
    organization: "Organization C",
    posterName: "Sample Poster",
    posterCollege: "",
    date: "Mar 22",
    time: "2PM",
    venue: "Laboratory",
    day: 22,
  },
  {
    id: "5",
    title: "Cultural Show",
    emoji: "🎭",
    organization: "Arts Council",
    posterName: "Sample Poster",
    posterCollege: "",
    date: "Mar 27",
    time: "5PM",
    venue: "Auditorium",
    day: 27,
  },
  {
    id: "6",
    title: "Debate Competition",
    emoji: "🎤",
    organization: "Debate Society",
    posterName: "Sample Poster",
    posterCollege: "",
    date: "Mar 23",
    time: "3PM",
    venue: "AVR",
    day: 23,
  },
];
