import type { AdviserEvent } from "./types";

export const initialPendingEvents: AdviserEvent[] = [
  {
    id: "1",
    name: "AI and Machine Learning Workshop",
    organization: "CCSICT",
    date: "Mar20",
    venue: "Gymnasium",
    status: "Pending",
    workflowStatus: "Pending Dean",
    description: "A comprehensive workshop on artificial intelligence and machine learning for CCSICT students.",
    eventType: "Student Event",
    purpose:
      "To enhance students' understanding of AI and ML concepts, and provide hands-on experience with modern AI tools and frameworks.",
    startTime: "8:00 AM",
    endTime: "5:00 PM",
    itemsEquipment: "Projector, laptops (30 units), tables, chairs, sound system, whiteboard",
    participants: "30",
    sdgs: "Quality Education, Industry, Innovation and Infrastructure",
    remarks: "Workshop requires stable internet connection for all participants.",
    createdBy: "Adviser",
    needsGSO: true,
    workflowHistory: [
      { name: "Dean", status: "current", timestamp: undefined, approver: undefined },
      { name: "GSO", status: "pending", timestamp: undefined, approver: undefined },
      { name: "OSAS", status: "pending", timestamp: undefined, approver: undefined },
      { name: "EO", status: "pending", timestamp: undefined, approver: undefined },
    ],
  },
  {
    id: "2",
    name: "Coding Bootcamp 2026",
    organization: "CCSICT",
    date: "Mar21",
    venue: "Devenecia",
    status: "Pending",
    workflowStatus: "Pending GSO",
    description: "Three-day intensive coding bootcamp focusing on web development technologies.",
    eventType: "Student Event",
    purpose:
      "To provide students with intensive hands-on training in modern web development frameworks and best practices.",
    startTime: "9:00 AM",
    endTime: "6:00 PM",
    itemsEquipment: "Projector, microphone system, laptops, extension cords, tables and chairs",
    participants: "50",
    sdgs: "Quality Education, Decent Work and Economic Growth",
    remarks: "Event runs for 3 consecutive days (Mar 21-23). Guest speakers from industry confirmed.",
    createdBy: "Adviser",
    needsGSO: true,
    workflowHistory: [
      { name: "Dean", status: "completed", timestamp: "Apr 28, 2026 - 10:30 AM", approver: "Dean Roberto Cruz" },
      { name: "GSO", status: "current", timestamp: undefined, approver: undefined },
      { name: "OSAS", status: "pending", timestamp: undefined, approver: undefined },
      { name: "EO", status: "pending", timestamp: undefined, approver: undefined },
    ],
  },
  {
    id: "3",
    name: "Cybersecurity Awareness Seminar",
    organization: "CCSICT",
    date: "Mar25",
    venue: "Open Gymnasium",
    status: "Pending",
    workflowStatus: "Pending EO",
    description: "Cybersecurity seminar covering online safety, data protection, and ethical hacking basics.",
    eventType: "Student Event",
    purpose:
      "To raise awareness about cybersecurity threats and educate students on protecting their digital identities and personal data.",
    startTime: "1:00 PM",
    endTime: "5:00 PM",
    itemsEquipment: "Projector, sound system, microphones, seating for 200 students",
    participants: "200",
    sdgs: "Quality Education, Peace, Justice and Strong Institutions",
    remarks: "Industry experts from cybersecurity firms will be guest speakers.",
    createdBy: "Adviser",
    needsGSO: true,
    workflowHistory: [
      { name: "Dean", status: "completed", timestamp: "Apr 26, 2026 - 2:00 PM", approver: "Dean Roberto Cruz" },
      { name: "GSO", status: "completed", timestamp: "Apr 27, 2026 - 11:00 AM", approver: "GSO Maria Lopez" },
      { name: "OSAS", status: "completed", timestamp: "Apr 28, 2026 - 3:45 PM", approver: "OSAS Director Carlos Ramos" },
      { name: "EO", status: "current", timestamp: undefined, approver: undefined },
    ],
  },
];

export const initialApprovedEvents: AdviserEvent[] = [
  {
    id: "5",
    name: "CCSICT Orientation Day",
    organization: "CCSICT",
    date: "Mar01",
    venue: "Gymnasium",
    status: "Approved",
    workflowStatus: "Approved",
    description: "Orientation day for new CCSICT students covering program requirements, facilities, and student opportunities.",
    eventType: "Student Event",
    purpose:
      "To welcome new CCSICT students and provide them with essential information about their academic journey and available resources.",
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    itemsEquipment: "Projector, sound system, microphones, tables, chairs for 300 students",
    participants: "300",
    sdgs: "Quality Education, Partnerships for the Goals",
    remarks: "Lunch will be provided. All CCSICT faculty are invited to participate.",
    createdBy: "Adviser",
    needsGSO: true,
    workflowHistory: [
      { name: "Dean", status: "completed", timestamp: "Apr 20, 2026 - 9:15 AM", approver: "Dean Roberto Cruz" },
      { name: "GSO", status: "completed", timestamp: "Apr 21, 2026 - 10:30 AM", approver: "GSO Maria Lopez" },
      { name: "OSAS", status: "completed", timestamp: "Apr 22, 2026 - 2:45 PM", approver: "OSAS Director Carlos Ramos" },
      { name: "EO", status: "completed", timestamp: "Apr 23, 2026 - 11:00 AM", approver: "Executive Officer Dr. Elena Santos" },
    ],
  },
];
