import type { OfficerEvent } from "./types";

export const initialPendingEvents: OfficerEvent[] = [
  {
    id: "1",
    name: "Sports Festival",
    date: "Mar20",
    venue: "Gymnasium",
    status: "Pending",
    workflowStatus: "Pending Adviser",
    description: "Annual sports festival for all departments.",
    purpose:
      "To promote physical fitness and camaraderie among students across all departments through friendly sports competitions.",
    startTime: "8:00 AM",
    endTime: "5:00 PM",
    itemsEquipment: "Sound system, tents, chairs, tables, sports equipment (basketballs, volleyballs, etc.)",
    remarks: "Please ensure the venue is available for setup one day before the event.",
    createdBy: "Organization",
    needsGSO: true,
    workflowHistory: [
      {
        name: "Student Officer",
        status: "completed",
        timestamp: "Apr 28, 2026 - 9:30 AM",
        approver: "Juan Dela Cruz",
      },
      { name: "Adviser", status: "current", timestamp: undefined, approver: undefined },
      { name: "Dean", status: "pending", timestamp: undefined, approver: undefined },
      { name: "GSO", status: "pending", timestamp: undefined, approver: undefined },
      { name: "OSAS", status: "pending", timestamp: undefined, approver: undefined },
      { name: "EO", status: "pending", timestamp: undefined, approver: undefined },
    ],
  },
  {
    id: "2",
    name: "Technology and Innovation Seminar",
    date: "Mar21",
    venue: "Devenecia",
    status: "Pending",
    workflowStatus: "Pending Dean",
    description: "A comprehensive seminar on emerging technologies and innovation strategies for students and faculty.",
    requesterName: "Maria Santos",
    requesterRole: "President",
    purpose:
      "To educate students about the latest trends in technology and innovation, preparing them for future careers in the tech industry.",
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    itemsEquipment: "Projector, microphone system, laptop, whiteboard, markers",
    letterContent:
      "Dear Adviser,\n\nWe, Computer Science Club, humbly request permission to conduct a Technology and Innovation Seminar on March 21, 2026 at Devenecia Hall.\n\nThis seminar aims to expose our students to cutting-edge technologies and innovative practices in the industry. We have invited guest speakers from leading tech companies who will share their expertise and experiences.\n\nWe kindly request your approval for this event and the use of the mentioned venue and equipment.\n\nRespectfully yours,\nMaria Santos\nPresident, Computer Science Club",
    remarks: "Guest speakers will arrive at 8:30 AM. Please ensure the venue is ready by then.",
    createdBy: "Organization",
    needsGSO: true,
    workflowHistory: [
      {
        name: "Student Officer",
        status: "completed",
        timestamp: "Apr 27, 2026 - 2:15 PM",
        approver: "Juan Dela Cruz",
      },
      {
        name: "Adviser",
        status: "completed",
        timestamp: "Apr 28, 2026 - 10:00 AM",
        approver: "Dr. Ana Torres",
      },
      { name: "Dean", status: "current", timestamp: undefined, approver: undefined },
      { name: "GSO", status: "pending", timestamp: undefined, approver: undefined },
      { name: "OSAS", status: "pending", timestamp: undefined, approver: undefined },
      { name: "EO", status: "pending", timestamp: undefined, approver: undefined },
    ],
  },
  {
    id: "3",
    name: "Music Festival 2026",
    date: "Mar22",
    venue: "Open Gymnasium",
    status: "Pending",
    workflowStatus: "Pending OSAS",
    description: "Music festival featuring local bands and student performers.",
    requesterName: "Pedro Reyes",
    requesterRole: "Event Coordinator",
    purpose: "To showcase local musical talent and provide entertainment for the student body.",
    startTime: "3:00 PM",
    endTime: "9:00 PM",
    itemsEquipment:
      "Stage setup, professional sound system, lighting equipment, generator, security barriers",
    letterContent:
      "Dear Adviser,\n\nMusic Society is writing to request approval for our annual Music Festival 2026, scheduled for March 22, 2026 at the Open Gymnasium.\n\nThis event has become a beloved tradition in our institution, bringing together students through music and celebration. We will feature five local bands and several student performers.\n\nWe respectfully request permission to use the Open Gymnasium and the necessary equipment listed above.\n\nThank you for your consideration.\n\nSincerely,\nPedro Reyes\nEvent Coordinator, Music Society",
    remarks: "Event may run slightly past 9:00 PM for cleanup. Security personnel needed.",
    createdBy: "Organization",
    needsGSO: true,
    workflowHistory: [
      {
        name: "Student Officer",
        status: "completed",
        timestamp: "Apr 25, 2026 - 11:45 AM",
        approver: "Juan Dela Cruz",
      },
      {
        name: "Adviser",
        status: "completed",
        timestamp: "Apr 26, 2026 - 3:20 PM",
        approver: "Dr. Ana Torres",
      },
      {
        name: "Dean",
        status: "completed",
        timestamp: "Apr 27, 2026 - 9:15 AM",
        approver: "Dean Roberto Cruz",
      },
      {
        name: "GSO",
        status: "completed",
        timestamp: "Apr 28, 2026 - 1:30 PM",
        approver: "GSO Maria Lopez",
      },
      { name: "OSAS", status: "current", timestamp: undefined, approver: undefined },
      { name: "EO", status: "pending", timestamp: undefined, approver: undefined },
    ],
  },
];

export const initialApprovedEvents: OfficerEvent[] = [
  {
    id: "5",
    name: "Welcome Assembly",
    date: "Mar01",
    venue: "Gymnasium",
    status: "Approved",
    workflowStatus: "Approved",
    description: "Freshmen welcome assembly introducing new students to campus life and academic expectations.",
    purpose: "To welcome incoming freshmen and introduce them to the university culture and resources.",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    itemsEquipment: "Projector, sound system, chairs for 500 students",
    remarks: "All department heads are expected to attend.",
    createdBy: "Organization",
    needsGSO: true,
    workflowHistory: [
      {
        name: "Student Officer",
        status: "completed",
        timestamp: "Apr 20, 2026 - 8:00 AM",
        approver: "Juan Dela Cruz",
      },
      {
        name: "Adviser",
        status: "completed",
        timestamp: "Apr 20, 2026 - 2:30 PM",
        approver: "Dr. Ana Torres",
      },
      {
        name: "Dean",
        status: "completed",
        timestamp: "Apr 21, 2026 - 10:15 AM",
        approver: "Dean Roberto Cruz",
      },
      {
        name: "GSO",
        status: "completed",
        timestamp: "Apr 22, 2026 - 9:00 AM",
        approver: "GSO Maria Lopez",
      },
      {
        name: "OSAS",
        status: "completed",
        timestamp: "Apr 23, 2026 - 3:45 PM",
        approver: "OSAS Director Carlos Ramos",
      },
      {
        name: "EO",
        status: "completed",
        timestamp: "Apr 24, 2026 - 11:20 AM",
        approver: "Executive Officer Dr. Elena Santos",
      },
    ],
  },
];
